name: GitHub Actions Demo
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1"
      - run: 
          echo "mkdir docker\n
            cd docker\n
            time=$(date "+%Y-%m-%d %H:%M:%S")\n
            echo '#'$time >> dockerfile\n
            echo 'print("HELLLLLO WORRRRRRLD")' >> hello.py\n
            echo "FROM python:3.6.2\n
            ADD ./hello.py /hello/\n
            WORKDIR /hello\nCMD [\"python\",\"hello.py\"]" >> dockerfile" >> script.sh"

