name: GitHub Actions Demo
on: [push]
jobs:
  job1:
      runs-on: ubuntu-latest
      steps:
          - run: echo "job1"
          - run: touch test.sh
          - run: echo "mkdir docker" >> test.sh
          - run: echo "cd docker" >> test.sh
          - run: echo 'time=$(date "+%Y-%m-%d %H:%M:%S")' >> test.sh
          - run: echo "echo '#'$time >> dockerfile" >> test.sh
          - run: echo "echo 'print("HELLLLLO WORRRRRRLD")' >> hello.py" >> test.sh
          - run: echo 'echo "FROM python:3.6.2' >> test.sh
          - run: echo "ADD ./hello.py /hello/" >> test.sh
          - run: echo "WORKDIR /hello" >> test.sh
          - run: echo 'CMD [\"python\",\"hello.py\"]" >> dockerfile' >> test.sh
          - run: cat test.sh
          - run: bash test.sh
          - run: ls ./docker
          - run: ls ./*




