name: GitHub Actions Demo
on: [push]
jobs:
  job1:
      runs-on: ubuntu-latest
      steps:
          - run: echo "job1"
          - run: ls src/*
          - run: ls ../
          - run: ls ../../
          - run: ls ../../../
          - run: cat test.sh
  job2:
      runs-on: ubuntu-latest
      steps:
          - run: echo "job2"
          - run: ls
          - run: cat test.sh


